### ISSUE TITLE
This resource creates too many versions

### ISSUE THREAD

**Issue by Rukenshia** [olhtbr/metadata-resource#1]
Hi,

we've recently run into an issue with your resource (and a few others that work more or less the same). The issue is that concourse, with every `check` interval, creates a new row `versioned_resource` for your resource. This means that after some time, there are **a lot** of rows for your resource. For your resource, we are talking 300k versions across all teams. This makes concourse reaaaally slow.

To fix this problem, the `check` script always needs to return an empty array and the users need to call the `put` step, which will be followed up by concourse with an implicit get step. Functionality will not really change, all the users have to do is change "get" to "put". We've done the same for our resource. Sadly, the `check` script still runs even with the `put` step, which is why I'm reaching out to you in the hopes that we can change this with you.

**Comment by olhtbr** [comment]
Hi @Rukenshia,

Thanks for letting me know of this issue! Sure, I'm up for changing this, it totally makes sense.
