### ISSUE TITLE
The pulled metadata is confliecting with previously pulled records

### ISSUE THREAD

**Issue by ryankschee** [olhtbr/metadata-resource#2]
Hi,

I am using the same job setup as your demo and I notice that the pulled metadata is not consistent across the time:
- Sometime it shows correct at pull, but when I try to cat metadata $BUILD_*, it shows data from any previous build.
- Sometime it show incorrect metadata at pull task. 

Did I miss out anything?

**Comment by olhtbr** [comment]
Hi @ryankschee,

I'm trying to reproduce your issue, but can't seem to do it. Which version of Concourse are you running? Can you post your pipeline code (in case it's not the exact copy paste of the example)? What are some examples of the wrong data it shows?

**Comment by plumenator** [comment]
I have the same issue. I think it's because multiple jobs `put` to the same resource and whichever finishes last overwrites the files.

**Comment by olhtbr** [comment]
Thanks, I see the problem now, let me figure out something next week.

**Comment by zwadderich** [comment]
Hi,

Do you have any update on this issue?

**Comment by olhtbr** [comment]
Sorry, I got bogged down with work. 2.0.1 now gives consistent metadata for multiple jobs running at the same time.

**Comment by scottillogical** [comment]
just found this, awesome thanks I was running into this issue for a while and was very confused, switched from a `get` to  `put` and its all gravy

**Comment by olhtbr** [comment]
great, I'm glad it's solved now for good!
