### ISSUE TITLE
Release ARM64 images

### ISSUE THREAD

**Issue by odidev** [olhtbr/metadata-resource#4]
Hi Team,

I am trying to use metadata-resource image on the arm64 platform but it seems the arm64 tag is not available for this image.

I have updated **busybox** tag to `1.33` as tag `1.26` does not have arm64 support and built the image successfully in the local arm64 machine.

I have built the image in Travis as well but for that first, we need to migrate from `travis-ci.org` to `travis-ci.com`.

Do you have any plans in releasing arm64 image?

If interested, I can raise a PR.

**Comment by olhtbr** [comment]
Hi @odidev,

I migrated the repo over to travis-ci.com and although I don't have much time to work on this, I would be happy to accept a PR.

**Comment by odidev** [comment]
Raised PR https://github.com/olhtbr/metadata-resource/pull/5. Please let me know your feedback.
